spring:
  datasource:
    username: root
    password: adminadmin
    url: jdbc:mysql://100.65.142.84:3306/exerciseGeinfor
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      dialect: org.hibernate.dialect.MySQLDialect